
# Default Robot Configuration

# WARNING: Changing the content of this folder effects the working of magni_bringup/scripts/launch_core.py !!!
# Make sure you understand what you're doing before changing anything in here. 


# ============================================= USER CHANGEABLE PARAMETERS =================================================

# Check for lidar and camera extrinsics files in two places with following priorities:
#  1.) in ~/.ros/extrinsics/<SENSOR>_extrinsics_<POSITION>.yaml
#  2.) in package magni_description/extrinsics/<SENSOR>_extrinsics_<POSITION>.yaml
# where <SENSOR> is either "camera" or "lidar" and <POSITION> is an arbitrary string with which the extrinsics file is identified
raspicam_position: 'forward' # to disable insert "None"
lidar_position : 'top_plate'  # to disable insert "None"

sonars_installed: False # to enable set to True, to disable set to False

force_time_sync : True
oled_display: {'controller': None}

# ============================================ ADMIN PARAMETERS FROM HERE DOWN ==============================================

ubiquity_motor:
  board_version : None 
  serial_port: '/dev/ttyAMA0'
  serial_baud: 38400
  serial_loop_rate: 200
  controller_loop_rate: 20
  pid_proportional: 5000
  pid_integral: 5
  pid_derivative: -110
  pid_denominator: 1000
  pid_moving_buffer_size: 70
  pid_velocity: 0
  pid_control:  0
  drive_type: "standard"
  wheel_type: "standard"
  wheel_gear_ratio: 4.294
  fw_max_pwm: 325

ubiquity_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

ubiquity_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  publish_rate: 50
  pose_covariance_diagonal: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
  twist_covariance_diagonal: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
  cmd_vel_timeout: 0.25

  enable_odom_tf: true

  wheel_separation : 0.33
  wheel_radius : 0.1015


  base_frame_id: base_footprint

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.1   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # rad/s^2